name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  name: print greeting
         run: echo "hello world"
      -  name: print goodbye
         run: echo "Done-bye"
      -  name: Multiple command
         run: |
           echo "first output"
           echo "second output"
